version: 2.1

jobs:
  build:
    parallelism: 15
    machine:
      image: ubuntu-2004-cuda-11.4:202110-01
    steps:
      - checkout
      - run : |
              chmod +x repo.sh
              ./repo.sh
